export const config = {
  HOST_HASH_SALT: 12,
  TICKET_HASH_SALT: 12,
  ADMIN_HASH_SALT: 12,
  TRENDING_EVENTS_LIMIT: 10,
  TRENDING_EVENTS_BY_CATEGORY_LIMIT: 10,
  TRENDING_EVENTS_BY_SUBCATEGORY_LIMIT: 10,
  NEAR_DISTANCE_IN_MILES: 50,
};
